### ISSUE TITLE
Should get NaN-values instead of zeroes for missing data when reprojecting onto a Domain

### ISSUE THREAD

**Issue by knutfrode** [nansencenter/nansat#104]
When reprojecting a Nansat object to a Domain, zero values are given for all bands for the part of the Domain which is not covered by the Nansat object.
Nansat should rather provide NaN in such cases.

**Comment by akorosov** [comment]
One solution I can image is to erase the out-of-swath values by a mask in Nansat._get_item(). The mask can be a band with known non-zero values (e.g. a band with ones added just before reproject or another band with known values). So this solution is rather heavy for every time use:
1. add band
2. reproject
3. get band with mask
4. get band with value
5. mask away out of swath values

What if we leave __get_item__ as it is and add Nansat.get_masked_array() which returns array with data where out-of-swath pixels are masked with nan?

Alternatively we can always add a masking band at the point of Nansat creation and use it afterwards.

**Comment by mortenwh** [comment]
With the alternative using a mask-band read by get_item, the user doesn't
need to know any "tricks" for getting the correct data. Although it may be
heavy, it is more user-friendly so I vote for that....

**Comment by akorosov** [comment]
One light-weight solution is to always add a pixel function that returns only ones. Then after reproject it will return ones only for the swath area (just tested that). That pixel function can be used for masking in __get_item__()

**Comment by akorosov** [comment]
After dadc473 :
Testing:
n = Nansat('A2014275111000.L2_LAC.NorthNorwegianSeas.hdf') # from FTP
d = Domain(4326, '-te -2 64 20 74 -tr 0.1 0.1')
n.reproject(d)
one_mask = n['one_mask']

**Comment by asumak** [comment]
I like this idea. I think it is a simpler way for developers.

**Comment by akorosov** [comment]
@knutfrode , @mortenwh , can you assess the idea? I added a band 'swathmask' to s1a, obpg_l2 and radarsat2 mappers. Now if you reproject data from these mappers it will come out masked with np.nan in out of swath pixels. Next steps: to add the band 'swathmask' to other L1/L2 mappers where required (e.g. not in NCEP, etc).

**Comment by akorosov** [comment]
Since we need that kind of mask only after reproject, I will move VRT._add_swath_mask_band into Nansat.reproject() and add (admask=True) option to control that.

**Comment by akorosov** [comment]
Now I'm happy:
 * We don't need to add that in every mapper. 
 * It is still flexible, we can do n.reproject(d, addband=False) and no masking band will be added/used.
Guys, are you good on merging to develop?

**Comment by asumak** [comment]
Great! It is a very clear and simple solution.
I agree with merging.

**Comment by akorosov** [comment]
Closed in ccbd39ed6f70d1086add877ca0a11348e93859bb
