### ISSUE TITLE
'factor' is not used in vrt.get_subsampled_vrt()

### ISSUE THREAD

**Issue by asumak** [nansencenter/nansat#105]
factor is not use in vrt.get_subsampled_vrt(self, newRasterXSize, newRasterYSize,factor, eResampleAlg).
can I delete it?

**Comment by asumak** [comment]
Fixed and run the test. (1b4cc7a)

**Comment by akorosov** [comment]
Why is it branched from #50? Difficult to understand the changes and to merge to develop.

**Comment by akorosov** [comment]
Merged to develop in c051ab9dbde2d396b2315829a2d2cc9aea2b110c
