### ISSUE TITLE
Docs in ReadTheDocs style/format

### ISSUE THREAD

**Issue by akorosov** [nansencenter/nansat#108]
http://readthedocs.org provides very useful platform for hosting documentation (and promotion). We should convert our docs to the format accepted by ReadTheDocs:

Make docs directory
Agree on structure
Update and move text from some Wiki-pages and code to docs/index.rst and other pages
Upload to the ReadTheDocs server and to gh-pages

**Comment by asumak** [comment]
Readthedoc dose not handle numpydoc. 
Switch to napoleon, because it is handled?

**Comment by mortenwh** [comment]
Also todo (ref #116): Replace wiki pages on github by a web page (ghpages) and readthedocs

**Comment by mortenwh** [comment]
This is now done in branch issue108-readthedocs - who can review it? See http://nansat.readthedocs.io/en/issue108-readthedocs/index.html

**Comment by aleksandervines** [comment]
I created some tasks on scrumdo to make sure the TODO's are not forgotten.

Got two additional suggestions:

Could we reference to nansat-lectures somewhere under user documentation?

Could we put "nansat" and "nansat.mappers" on a new level, e.g. under User Documentation/Python Modules - I feel it's a bit out of place as it is now. Also, is it possible to remove the "nansat" level, and go straight on nansat package?
Then structure would become something like:
- User doc
  - installation
  - Python Modules
    - nansat package
    - nansat.mappers package

**Comment by mortenwh** [comment]
Ok - all this is now done. Regarding the last point (3rd indented bullet list) it must, however, be like before:

* nansat
* nansat.mappers package

This is because that content is auto-generated....

**Comment by mortenwh** [comment]
Last changes committed and compiled at http://nansat.readthedocs.io/en/issue108-readthedocs/index.html

@akorosov - can you have a last review?

**Comment by akorosov** [comment]
Hi @mortenwh , the docs look really great now! I provide few suggestions. You can decide if you want to incorporate them.

### 1
Move
```
We appreciate acknowledments of Nansat. Please add “The image analysis was performed with the open-source Nansat (https://github.com/nansencenter/nansat) python package” (or equivalent) if you use Nansat in scientific publications.
```
to a separate section  Acknowledgement and add Full reference to he paper:
```
Korosov A.A., Hansen M.W., Dagestad K.-F., Yamakawa A., Vines A., Riechert M., (2016). Nansat: a Scientist-Orientated Python Package for Geospatial Data Processing. Journal of Open Research Software. 4(1), p.e39. DOI: http://doi.org/10.5334/jors.120
```
### 2
Simplify installation instructions. I think we have to say: Install anaconda[lnk to anaconda] and then:
```
conda install -q --yes -c conda-forge gdal numpy pillow netcdf4 cfunits python-dateutil pythesint nose
pip install https://github.com/nansencenter/nansat/archive/master.tar.gz
```
Nothing more.

### 3
In Nansat Tutorial provide link to the folder notebooks:
https://github.com/nansencenter/nansat-lectures/tree/master/notebooks

### 4
In nansat modules (http://nansat.readthedocs.io/en/issue108-readthedocs/source/modules.html)
Leave only entries for individual modules (e.g., vrt, domain, nansat, figure, etc) and remove 'Submodules' and 'nansat package'

### 5
In the 'Feature documentation' all four links lead to the same webpage. Leave just one link.

**Comment by mortenwh** [comment]
1. Ok
2. I've added the conda line to the anaconda installation section but we also need to have simple descriptions of how to install with the other methods. In principle, I agree that we could remove the requirements but then we first need to make sure that all the installations properly bring in dependencies as well...
3. ok
4. This is not possible, since the layout is created automatically (see comment by @alevin and my answer as well)...
5. ? I don't see any repetion.... There are 8 links to different pages and datasets...

**Comment by mortenwh** [comment]
ok, point 5 referred to the links on the landing page. This will not be changed...

**Comment by aleksandervines** [comment]
fyi, cfunits is not on conda.

**Comment by mortenwh** [comment]
why did you reopen?

**Comment by mortenwh** [comment]
@akorosov - I will now merge into develop and close this issue unless you have a good reason not to....

**Comment by aleksandervines** [comment]
Something weird is going on, as Anton was not aware that he kept reopening issues.
