### ISSUE TITLE
Nansat.get_transect() uses awkward dict to return values

### ISSUE THREAD

**Issue by akorosov** [nansencenter/nansat#113]
It is not convenient to use dictionaries with string keys to get values from the Nansat.get_transect() function. In such case a user first need to know the keys.

Suggested interface:
```values, lon, lat, pix, line = n.get_transect()```
'values' is list of lists of lists;
lon, lat, pix, line are lists of lists;
```
values = [
    [
        [first_transect_first_band],
        [first_transect_second_band],
        [first_transect_third_band]
    ],
    [
        [second_transect_first_band],
        [second_transect_second_band],
        [second_transect_third_band]
    ]
]

lon = [
    [first_transect],
    [second_transect],
]
# lat, pix, line - are similar to lon
```
Examples:
* from first transect, second band, access third value ```val = values[0][1][2]```
* all values in case of single transect, single band ```values = values[0][0]```
* Plot first band against lat: ```plot(values[0][0], lons[0])```

It is tempting to reduce dimentionality in case of one band and one transect but in case of automatic scripts that will make it difficult for a user to use it in a generic way. So I suggest to always return data with same dimensionality.

**Comment by asumak** [comment]
Changed from dictionaries to lists. (ecacf38)
Currently three variables are returned as "values, lonlat, pixline = n.get_transect()".
Is it better to return as "values, lon, lat, pix, line = n.get_transect()" ?

**Comment by mortenwh** [comment]
This problem is also in the master branch where it should definitely not be... Also the master branch version does not draw lines between the points. I suggest to revert the get_transect function in master to a previous version, when the return variables were `t,[lon,lat],p` (is that how it is now in develop, i.e. lonlat is a list?). Ok?

When changes like these are made, please make sure it is backward compatible and provide warnings of planned changes that will cause backward incompatibility... And write tests....

**Comment by mortenwh** [comment]
I have switched back the get_transect-function to 9a185f000aa4a4714eeacb0de8b05bddae9abf9c in branch issue113-based-on-master now (see 4414fa6fd6ecffa19533d528eb82b18ff2f4855e). I propose to merge this back into master but need feedback on whether this is ok or not. Is anyone using the get_transect-function in master?

@asumak, can you follow up with finishing this issue in develop?

**Comment by mortenwh** [comment]
I won't merge branch issue113-based-on-master - will just use it for own needs in that branch. New proper version of this function should come in develop (future release v0.7). The current master v0.6 will be kept as it is.

**Comment by akorosov** [comment]
The method get_transect became 200 lines long and needs complete refactoring
