### ISSUE TITLE
Radarsat2['IncidenceAngle'] and ['SAR_look_direction'] return None

### ISSUE THREAD

**Issue by asumak** [nansencenter/nansat#122]
GDAL cannot read array('SAR_look_direction') and array('incidence_angle') from "RS2_20150218_055124_0086_SCNA_HHHV_SGF_379174_2171_10901930".

**Comment by mortenwh** [comment]
Is it only that file? Can you write some tests using several datasets, and
debug it? I don't have time to investigate this in detail now...

**Comment by mortenwh** [comment]
Is this now solved?

**Comment by asumak** [comment]
Yes, It was a machine problem (Johansen). I close this issue.
