### ISSUE TITLE
Mosaic fails after swathmask is introduced

### ISSUE THREAD

**Issue by mortenwh** [nansencenter/nansat#126]
#### Problem
Mosaic.average cannot get data from averaged object in _average_one_file
#### Solution
* Switch from mp.Queue() to mp.Pool().map()
* Debug

**Comment by akorosov** [comment]
First version merged into develop in 2282596b3e9228700842c6b5d1db6e67f61bd42f
Remaining issues:
Median and Latest still don't work. Tests for Mosaic.median() and latest() don't exist.

**Comment by akorosov** [comment]
the bug was actually fixed. Mosaic.median() and Mosaic.latest() are other issues.
