### ISSUE TITLE
Testing conventions

### ISSUE THREAD

**Issue by mortenwh** [nansencenter/nansat#132]
I have proposed some conventions for testing in the [nansat conventions page](https://github.com/nansencenter/nansat/wiki/Nansat-Conventions).

Tasks under this issue:
* agree on the conventions
* update folder structure accordingly

**Comment by akorosov** [comment]
I agree with the suggestions.

**Comment by mortenwh** [comment]
Closed with ee122d7a59b238a95fab74f8aeec0fbc2928f57c
