### ISSUE TITLE
is it possible to write 16 bit GeoTIFF  with nansat (with 16 bit colormap)?

### ISSUE THREAD

**Issue by evgeny-a-morozov** [nansencenter/nansat#135]
Hi guys!
write_geotiffimage writes an 8-bit GeoTiff image for a given band, I wonder is it possible to expand it to 16 bit option?
What I have figured out so far is that 
gdal.GDT_Byte should be replaced with
gdal.GDT_UInt16

resulting GeoTIFF is really 16 but, but I am doing something wring with colormap
keeping colormap  length as 256 produces image files, but they are not readable with common image viewers due to messed up colourmap (Nansat reads ok)

simply rescaling from 256 to 65536 gives error
(File "/home/evgeny/nansat/nansat/nansat.py", line 1282, in write_geotiffimage
    colorTable.SetColorEntry(i, colorEntry)
 .......
TypeError: Invalid values in ColorEntry sequence )

apparently it happens when colormap created is longer than 32768 (worked for 32768 )

does anyone know if this problem is common and/or solvable?
does Nansat need and extended write_geotiffimage in order to switch between 8 and 16 bit geotiff?

Thank you

**Comment by akorosov** [comment]
write_geotiffimage is intended to write only 256 colours images. For exporting actual data it is better to use Nansat.export(driver='GTiff')
