### ISSUE TITLE
Switch Basemap with Cartopy

### ISSUE THREAD

**Issue by akorosov** [nansencenter/nansat#140]
#### Problem

Basemap seems to be more and more outdated and is rather difficult to install. On the opposite Cartopy http://scitools.org.uk/cartopy/ is nice and simple. It seems to be at lower level but that's even better for development. 
#### Solution

Replace Basemap with Cartopy.
Change Domain.write_map and Nansatmap accordingly.

**Comment by akorosov** [comment]
Moved to Nansatmap repo

**Comment by akorosov** [comment]
We still use Basemap in write_domain_map function. It should be replaced with cartopy.

**Comment by korvinos** [comment]
closed in  #462
