### ISSUE TITLE
Harmonize get_time() and start_time()

### ISSUE THREAD

**Issue by akorosov** [nansencenter/nansat#143]
#### Problem
get_time() and start_time() is overlapping, both are a bit awkward to use, end_time() exists to complete the inconsistency. Besides names are not compatible with existing standards.
#### Solution
Define two functions:
get_time_coverage_start(self, bandID=None)
get_time_coverage_start(self, bandID=None)

Both functions return only one datetime object. If bandID is not specified that's the global time for the dayaset, if bandID is specified that's time for the specific band.

**Comment by akorosov** [comment]
And by the way, why n.sensor() is better than n.get_metadata('sensor') ? All .sensor() .satellite() and .source() should of course be removed.

**Comment by mortenwh** [comment]
well - it is much shorter and simpler to use that n.get_metadata...
besides, one doesn't need to know the key-name if we have these functions

**Comment by akorosov** [comment]
The problem is in consistency. I think we should keep consistent access to all metadata in the same way. If a method doesn't add to functionality - it is not worth adding. E.g. get_time() or start_time() convert from string representation of time to datetime object. And get_time_coverage_start will do that automatically for a band or for entire dataset - that's the gain in adding this method.
Maybe 'of course' was an exaggeration but I really want to keep Nansat simple and consistent :)

**Comment by aleksandervines** [comment]
How are you supposed to know what metadata that you can request with get_metadata? Do you have to print the object and go through all the text?

I am not familiar with working on nansat, but it seems more logical for me to use methods like get_sensor() and get_time_coverage_start() for metadata that is supposed to be available on all datasets.

For me, it seems more convenient to check what options that are available with methods, just write n.get_<tab> (the <tab> would depend on your choice of editor), than having to figure out what metadata that is available for you to call as parameter in n.get_metadata('sensor') || n.get_metadata('time_coverage_start'), And there is no code completion for text strings in editors so you will have to either write the whole thing or copy-paste.

**Comment by akorosov** [comment]
Instead of getters and setters in the get_...() way we can use pure Pythoicn '@property' decorator:
http://www.python-course.eu/python3_properties.php
time0 = n.time_coverage_start
Relevant for #120 as well

**Comment by akorosov** [comment]
An example of a class with dynamic attributes for each standard name in wkv.xml:
```
from nansat.node import Node

class CFVariable(unicode):
    ''' Abstraction to enable adding attributes to a unicode object '''
    pass

class CFVariables(object):
    ''' Thesaurus for all CF-variables (former WKVs) '''
    def __init__(self, xmlFileName):
        ''' Dynamically add attributes to thesaurus

        Go through 2-level XML file nansat/nansat/wkv.xml. First level is
        list of CF-Variable, second level is CF-attributes.
        Attributes of the CFVariables instance will be standard names (level 1)
        Attributes of standard names will be CF-attributes (level 2)

        Parameters:
        -----------
            xmlFileName : str or unicode
                path to wkv.xml file

        Modifies:
        ---------
            Adds attributes and atribute of atributes

        Example:
        --------
            # BTW: easy to access by tab-completion in IPython
            cfvars = CFVariables('nansat/nansat/wkv.xml')
            nameAsString = cfvars.wind_speed
            unitsAsString = cfvars.wind_speed.units
            longnameAsString = cfvars.wind_speed.long_name

        '''
        # read contents of XML file using convenient class Node
        n = Node.create(xmlFileName)

        # go through immediate children (CF-variables)
        for child in n.children:
            # add CF-variable as an attribute
            setattr(self, child['standard_name'], CFVariable(child['standard_name']))
            # access that CF-variable
            cfvAttr = getattr(self, child['standard_name'])
            # go through children of the CF-variable
            for grandchild in child.children:
                # add CF-variable children as attributes
                setattr(cfvAttr, grandchild.tag, grandchild.value)


cfvars = CFVariables('/home/antonk/py/nansat/nansat/wkv.xml')
nameAsString = cfvars.wind_speed
unitsAsString = cfvars.wind_speed.units
longnameAsString = cfvars.wind_speed.long_name
```
