### ISSUE TITLE
netcdf file is not always closed

### ISSUE THREAD

**Issue by aleksandervines** [nansencenter/nansat#149]
scipy.io.netcdf.netcdf_file(filename, mode='r', mmap=None, version=1)[source]
mmap : None or bool, optional
Whether to mmap filename when reading. Default is True when filename is a file name, False when filename is a file-like object. Note that when mmap is in use, data arrays returned refer directly to the mmapped data on disk, and the file cannot be closed as long as references to it exist.

I've gotten error messages that file can not be closed because of this.

**Comment by akorosov** [comment]
@aleksandervines , can you give example of code ? The best is to add a test, of course

**Comment by akorosov** [comment]
@aleksandervines ,can you add an example here? Or a test?
