### ISSUE TITLE
Nansat tutorials with usage show cases not available

### ISSUE THREAD

**Issue by mitkin** [nansencenter/nansat#151]
Would you consider pushing the notebooks themselves to the nansats git repo? Github can display `*.ipynb` files, so it would be even easier to handle them.

The tutorials in question: https://github.com/nansencenter/nansat/wiki/Tutorial

PS. Hello Anton, Morten and others. :)

**Comment by akorosov** [comment]
Thank you, @mitkin ! The wiki-page was updated. Regards :)

**Comment by mitkin** [comment]
Cool! 

PS. You guys made an impressive package!
