### ISSUE TITLE
Weak dependence on nersc-metadata

### ISSUE THREAD

**Issue by akorosov** [nansencenter/nansat#152]
Since nersc-metadata is not in pypi it is difficult to install it for a regular user. Hence installation of Nansat is also more complicated.
Move 'import nersc-metadata' to tools
wrap in try/except
In all mappers nersc-metadata is imported from tools. If None, WrongMapperError is raised.

**Comment by mortenwh** [comment]
Why not just add nerscmetadata to setup.py in Nansat? I have done that now in 627fb530a55b75ce79003a236c9d4f9a26610b60 (branch ```installwithmetadep``` - seems to work locally.

However, travis fails with ```The command "conda update -q --yes conda" failed and exited with 127 during .```

**Comment by akorosov** [comment]
Nersc-metadata is added to setup.py as a dependency and is directly installed by pip from github.com
