### ISSUE TITLE
Sentinel 1A mapper problems with EW GRDM

### ISSUE THREAD

**Issue by akorosov** [nansencenter/nansat#156]
n = Nansat('S1A_EW_GRDM_1SDH_20160124T041543_20160124T041643_009631_00E07E_300F.SAFE')
gives:
/home/antonk/py/nansat/nansat/nansat.pyc in __init__(self, fileName, mapperName, domain, array, parameters, logLevel, **kwargs)
    160         if fileName != '':
    161             # Make original VRT object with mapping of variables
--> 162             self.vrt = self._get_mapper(mapperName, **kwargs)
    163         # ...create using array, domain, and parameters
    164         else:

/home/antonk/py/nansat/nansat/nansat.pyc in _get_mapper(self, mapperName, **kwargs)
   1703                                                     gdalDataset,
   1704                                                     metadata,
-> 1705                                                     **kwargs)
   1706                     self.logger.info('Mapper %s - success!' % iMapper)
   1707                     self.mapper = iMapper.replace('mapper_', '')

/home/antonk/py/nansat/nansat/mappers/mapper_sentinel1a_l1.pyc in __init__(self, fileName, gdalDataset, gdalMetadata, **kwargs)
    192             xml = self.read_xml(noiseDict[key])
    193             noise_LUT_VRT = self.get_LUT_VRTs(xml, 'noiseVectorList',
--> 194                                               ['noiseLut'])[0]
    195             self.bandVRTs['LUT_noise_VRT_'+pol[key]] = (
    196                 noise_LUT_VRT['noiseLut'].get_resized_vrt(

/home/antonk/py/nansat/nansat/mappers/mapper_sentinel1a_l1.pyc in get_LUT_VRTs(self, XML, vectorListName, LUT_list)
    468         for LUT in LUT_list:
    469             LUTs[LUT] = np.array(LUTs[LUT])
--> 470         Ym = np.array([Y, ]*np.shape(X)[1]).transpose()
    471 
    472         lon, lat = self.transform_points(X.flatten(), Ym.flatten())

IndexError: tuple index out of range

**Comment by mortenwh** [comment]
Remember issue #145 - this could perhaps be solved just by using the gdal driver..

**Comment by akorosov** [comment]
Seems to work OK on available GRDM  data
