### ISSUE TITLE
interactive pointbrowser in crop is broken

### ISSUE THREAD

**Issue by aleksandervines** [nansencenter/nansat#157]
I believe crop with the pointbrowser is broken:

It uses PointBrowser.coordinates which has been modified.

**Comment by akorosov** [comment]
I don't understand. Can you add lines of code that you think fail?
It should be used this way:
pts = n.digitize_points()
t = n.get_transect(pts[0], ['L_469'], lonlat=False)

**Comment by aleksandervines** [comment]
Sorry, I was unclear.

Calling _nansat.crop()_ without any parameters will bring up interactive point-browser and, I believe, try to fetch coordinates based on the "old" version of PointBrowser.

`n.crop()`

These lines, (which are hard to unittest since they are based on interactivity):
```
if (xOff == 0 and yOff == 0 and
                xSize is None and ySize is None and
                lonlim is None and latlim is None):
            factor = self.resize(width=1000)
            data = self[1]
            browser = PointBrowser(data)
            browser.get_points()
            points = np.array(browser.coordinates)
            xOff = round(points.min(axis=0)[0] / factor)
            yOff = round(points.min(axis=0)[1] / factor)
            xSize = round((points.max(axis=0)[0] - points.min(axis=0)[0]) /
                          factor)
            ySize = round((points.max(axis=0)[1] - points.min(axis=0)[1]) /
                          factor)
            self.undo()
```

**Comment by akorosov** [comment]
Aha, I see.

BTW, Do you think splitting crop() in two functions crop() and crop_interactive() would be desirable here?

**Comment by aleksandervines** [comment]
In general I'd like a lot more, but smaller methods. So that would mean to split up methods like this, place the interaction code in one, and make it call the other for the crop. I think that could lead to an easier implementation of the single responsibility principle if we ever get there. The Nansat class is way too big and does too much.

On another note, I need to figure out best practice/standard patterns on using a class like PointBrowser in Python so that we can use a mock object to test the method.
