### ISSUE TITLE
May i remove node.find_dom_child?

### ISSUE THREAD

**Issue by aleksandervines** [nansencenter/nansat#161]
Pro:
1. I don't see it used anywhere (neither in Nansat, nor our other repositories on github)
2. It is a object method, but does no work on the object at all (other than calling the method itself recursively) - this method has nothing to do in an object.
3. There are no tests for it.
4. It has multiple "print" methods - I believe this is typically showing that this method is not in "production".
5. The node.node() method replaces this functionality - although not on a "dom" object.

Con:
It might be used in 3rd party code using Nansat

```
 def find_dom_child(self, dom, tagName, n=0):
        '''Recoursively find child of the dom'''
        children = dom.childNodes
        theChild = None

        chn = 0
        for child in children:
            print child, child.nodeType, chn
            if child.nodeType == 1:
                print child.tagName
                if str(child.tagName) == tagName:
                    print child.tagName, tagName, 'OK'
                    if chn == n:
                        theChild = child
                    chn += 1

            if theChild is not None:
                break

            if child.hasChildNodes():
                print 'has childs'
                theChild = self.find_dom_child(child, tagName, n)

        return theChild
```

I will remove _replace_dom_Node - it is a private method which is not used in the class (nor anywhere else I can find).

**Comment by akorosov** [comment]
Just remove both.

**Comment by akorosov** [comment]
Done in fe326fa989c74b264835f3353bac869753f12f28
