### ISSUE TITLE
Reprojection time

### ISSUE THREAD

**Issue by xdenisx** [nansencenter/nansat#163]
Hello everyone, 

I have found a problem with reprojection of a pair of S1a objects onto the common grid obtained from the polygons intersection. I do the following:

```
from nansat import Nansat, Domain
from shapely.wkt import loads
from osgeo import ogr

n1 = Nansat(f1)
n2 = Nansat(f2)

poly1 = loads(n1.get_border_wkt())
poly2 = loads(n2.get_border_wkt())

wkt = poly2.intersection(poly1).wkt
geom = ogr.CreateGeometryFromWkt(wkt)
env = geom.GetEnvelope()

srsString = '+proj=stere +lon_0=%f +lat_0=%f +no_defs' % (0., 70.)
extentString = '-lle %f %f %f %f -tr 100 100' % (env[0], env[2], env[1], env[3])

dStereo = Domain(srsString, extentString)

n1.reproject(dStereo, eResampleAlg=0)
n2.reproject(dStereo, eResampleAlg=0)

n1.write_figure('blablabla.tif', bands=['sigma0_HV'], clim=[0, 0.05], logarithm=True, cmapName='gray')
n2.write_figure('blablabla.tif', bands=['sigma0_HV'], clim=[0, 0.05], logarithm=True, cmapName='gray')
```
It takes ~1 hour for two S1a EW scenes, but if I do it separetely using its natural domain it takes a few minutes. Any ideas?

**Comment by akorosov** [comment]
Hi @xdenisx ! What do you mean by 'natural domain' - no reprojection? Then there is no data resample and the only thing GDAL does is reading of data from file and writing to another file. When you reproject, GDAL has to resample the image in addition, which takes a lot of time.

**Comment by xdenisx** [comment]
Hi Anton, I mean the following:

```
lon, lat = n.get_border()
n.reproject_GCPs('+proj=stere +lon_0=%f +lat_0=%f +no_defs' % (lon.mean(), lat.mean()))
n.vrt.tps = True
```
Actualy this is also reprojection but in this case it takes a few minutes.

**Comment by akorosov** [comment]
I still don't get it. With these commands you don;t do any reprojection of the gridded data. Only changing the projection of the ground control points (GCPs).

Generally reprojection time largely depends on the extent of the destination Domain. '-lle' option is not optimal in the <extentString>. Usually it works fine but sometimes it creates too large domain. Can you specify the sizes of the overlap domain (from the example above) and the 'natural' domain?

**Comment by xdenisx** [comment]
ok, it is becoming clear...
Here it is:

Intersection of domains: [5666 x 5868]
Initial domain of n1:        [10403 x 6826]
Initial domain of n2:        [10389 x 11756]

**Comment by akorosov** [comment]
n.reproject_GCPs makes sense only a s first step BEFORE actual n.reproject(...) It changes spatial reference system of GCPs and makes reprojection more accurate (tps=True, makes it even more accurate but much slower). So the workflow should be like:
# get intersection
# define domain
dstDomain =Domain(srsString, extString)
# change spatial reference system of GCPs
n.reproject_GCPs(srsString)
# do actual reprojection of Nansat
n.reproject(dstDomain, tps=True)
# write figure (read data from file, do actual resampling of gridded data, write to grafic file)
n.write_figure(...)

BTW, for feature tracking it is best not to reproject at all. You can always do feature tracking on original image and the convert row/column coordinates to lon,lat using n.transform_coordinates(). That's much faster.

**Comment by xdenisx** [comment]
Thanks, @akorosov! I'll let know on results.
