### ISSUE TITLE
Make a class border to simplify the border-methods in domain.py

### ISSUE THREAD

**Issue by mortenwh** [nansencenter/nansat#166]
Docs say get_border returns 10 points along each side but it is actually 11 points...
```
 595     def get_border(self, nPoints=10):
 596         '''Generate two vectors with values of lat/lon for the border of domain
 597 
 598         Parameters
 599         -----------
 600         nPoints : int, optional
 601             Number of points on each border
...
 618             rcVector1[n] = range(0, sizes[n], step)[0:nPoints]
```

Could the border instead be an object with the number of points along each side as attributes?

The reason for coming to this is that I am working on a dataset with sub-swaths with different borders. I want to join these borders to only have one border geometry with left, right, upper, and lower sides instead of 5 border geometries in my case. With a border class this would probably also be easier.

**Comment by akorosov** [comment]
Can you rather use Union of geometries?
from osgeo import ogr
poly1 = n1.get_border_geometry()
poly2 = n2.get_border_geometry()

union = poly1.Union(poly2)

print union.ExportToWkt()
A Border class would overload Nansat and blur focus.
