### ISSUE TITLE
Interpolation problem on converting LUT values into full resolution image grid?

### ISSUE THREAD

**Issue by jeong1park** [nansencenter/nansat#167]
Sentinel-1 mapper seems to have a problem on importing look up tables from metadata and converting them into the same grid of image data. The following screen shot shows an example of this problem. Star symbol indicates look up table values extracted from noise power profile, and dot symbol indicates import result using nansat mapper. test data ID: S1A_EW_GRDM_1SDH_20160124T072720_20160124T072820_009633_00E08A_6795

**Comment by akorosov** [comment]
Option can be added to the sentinel1a_l1 mapper which tells to interpolate using row/column data and not lon/lat. That will require full size matrices to be created by the mapper.
