### ISSUE TITLE
SMOS support

### ISSUE THREAD

**Issue by CzendaZdenda** [nansencenter/nansat#168]
Hi there,

does Nansat support SMOS data? Or when can I found the list of currently supported formats/missions?

Thank for answer,
Zdenek

**Comment by akorosov** [comment]
Hi Zdenek,
the list of some supported data is available here:
https://github.com/nansencenter/nansat/blob/master/nansat/mappers/README.yml

If SMOS data is in a netCDF file, gridded and followed CF-conventions (e.g. a file from [SMOS-BEC]( http://www.smos-bec.icm.csic.es/), then it can be read by the generic mapper. If it is L2 and is point data on hexagonal grid, then I'm afraid not.
