### ISSUE TITLE
sentinel-1 mapper error

### ISSUE THREAD

**Issue by tdcwilliams** [nansencenter/nansat#170]
I am in branch master and was trying to browse some sentinel-1 images
eg on johansen:
/Data/sim/tim/Sat-Images/S1A/

n=nansat.Nansat(filename) gave the error
'Mapper' object has no attribute '_set_time'

I haven't run nansat for a while on my machine, but I tried a radarsat2 file and that opened ok.

**Comment by akorosov** [comment]
@tdcwilliams , file name? Nansat version/branch?

**Comment by tdcwilliams** [comment]
Hi Anton,

nansat branch master (version is usual one?
https://github.com/nansencenter/nansat; running locally on osx 10.10)

any of files in:
/Data/sim/tim/Sat-Images/S1A

Regards,
Tim

**Comment by akorosov** [comment]
Hi Tim,

can you add access to these files to others?
chmod o+rx /Data/sim/tim/Sat-Images/S1A -R

Anton

**Comment by tdcwilliams** [comment]
sure, it is changed now
Tim

**Comment by tdcwilliams** [comment]
Hi Anton
changing the permissions didn't help - same error:

'Mapper' object has no attribute '_set_time'

regards
Tim

**Comment by mortenwh** [comment]
Have you tried the develop version of nansat? @akorosov - perhaps time to merge? Or should we just fix this in master?

**Comment by akorosov** [comment]
I cannot reproduce the error neither with develop nor with master. I'll try to help Tim in his office next week.

**Comment by akorosov** [comment]
An outdated .pyc file with an old version of mapper was causing the trouble.
