### ISSUE TITLE
The documentation at http://nansencenter.github.io/nansat is outdated

### ISSUE THREAD

**Issue by sebastianfast** [nansencenter/nansat#171]
Hi, I think I found an [outdated entry](http://nansencenter.github.io/nansat/nansat.nansat.html#nansat.nansat.Nansat.crop) in the wiki. The actual code does not accept `lonlim` and `latlim` anymore, but has a separate method `crop_lonlat(...)` instead. Best, Sebastian

**Comment by akorosov** [comment]
Thank you, @Fast007 ! We will need to update the webpage from the new code.

**Comment by mortenwh** [comment]
I have deleted the ghpages branch
