### ISSUE TITLE
Geolocation Accuracy

### ISSUE THREAD

**Issue by stefanmuckenhuber** [nansencenter/nansat#181]
Hi,

is there an estimate of the geolocation accuracy for Sentinel-1 images when I use n.transform_points() in Nansat?

To increase the accuracy, I reproject the image onto a stereographic projection around the centre of the image and use the spline interpolation function (n.vrt.tps = True). I had some problems with the accuracy before I introduced these steps, but they seem to be gone now...

I assume the closer to the ground control points the better...is there maybe an estimate of the accuracy range in meters?

Cheers,
Stefan

**Comment by akorosov** [comment]
Accuracy of Sentinel-1 ground control points is not controlled by Nansat.
Nansat cannot provide an estimate of geolocation accuracy without a priori information.
