### ISSUE TITLE
Assert overlap of source and destination domains for reprojection

### ISSUE THREAD

**Issue by mortenwh** [nansencenter/nansat#189]
A&nbsp;test is created in ```nansat_integration_tests.test_open_issues.py``` - this needs to be checked further

**Comment by mortenwh** [comment]
It is probably just one of the subswaths that doesn't fall within the given domain...

**Comment by akorosov** [comment]
It does not have to fail. It may as well return empty array and give a warning.

**Comment by mortenwh** [comment]
There is already a method ```overlaps``` in  the Domain-class. This could be called from reproject...

**Comment by mortenwh** [comment]
strange things happening - I don't think I closed this issue by intention....

**Comment by mortenwh** [comment]
Some notes and questions..:

1. The test created in ```nansat_integration_tests.test_open_issues``` is not sufficient. The domain and nansat object created in the test overlaps. We also need to test geometries that do not overlap. But given the below comments, @akorosov is probably correct...

2. Timing of reprojection without the overlap assertion vs the timing with overlap assertion is done with ```time python test_reproject.py``` given below.

        #!/usr/bin/env python
        from nansat.nansat import Nansat
        from nansat.domain import Domain
        from nansat.nsr import NSR
        fn = '/mnt/10.11.12.232/sat_downloads_asar/level-0/2010-01/descending/VV/gsar_rvl/RVL_ASA_WS_20100110211812087.gsar'
        n = Nansat(fn)
        xlon, xlat = n.get_corners()
        d = Domain(NSR(3857),'-lle %f %f %f %f -tr 1000 1000' % (xlon.min(), xlat.min(), xlon.max(), xlat.max()))
        n.reproject(d)

    a. Output without assertion:

        real: 0m39.612s
        user: 0m5.481s
        sys: 0m2.512s

    b. Output with assertion:

        real: 0m47.072s
        user: 0m5.980s
        sys: 0m3.100s

    c. I guess this favours the comment by @akorosov above, so I will not add any assertion
3. I found something else: 

    a. When making a Nansat object of the world topography, checks of intersection and overlap of the topography domain vs the SAR image returns False. This must be wrong, right? See code and figure below...

    b. Initialise objects:

        from nansat.nansat import Nansat
        from nansat.domain import Domain
        from nansat.nsr import NSR
        topo = Nansat('/mnt/10.11.12.231/sat_auxdata/dem/gmted30/gmted2010_30.vrt')
        fn = '/mnt/10.11.12.232/sat_downloads_asar/level-0/2010-01/descending/VV/gsar_rvl/RVL_ASA_WS_20100110211812087.gsar'
        n = Nansat(fn)
        xlon, xlat = n.get_corners()
        d = Domain(NSR(3857),'-lle %f %f %f %f -tr 1000 1000' % (xlon.min(), xlat.min(), xlon.max(), xlat.max()))

     c. Check with ```Domain.overlap()``` (which uses ```osgeo.ogr.Geometry.Intersects```):

        In [10]: topo.overlaps(n)
        Out[10]: False
        In [11]: topo.overlaps(d)
        Out[11]: False

    d. Check with ```osgeo.ogr.Geometry.Overlaps```:

        tgeom=topo.get_border_geometry()
        ngeom=n.get_border_geometry()
        dgeom=d.get_border_geometry()

        In [18]: tgeom.Overlaps(dgeom)
        Out[18]: False

        In [19]: tgeom.Overlaps(ngeom)
        Out[19]: False

        In [20]: dgeom.Overlaps(ngeom)
        Out[20]: True

        In [21]: ngeom.Overlaps(dgeom)
        Out[21]: True

Here are the geometries plotted (topography borders on the image edges, then domain borders, then SAR borders):

![screen shot 2018-01-25 at 18 38 26](https://user-images.githubusercontent.com/109061/35403108-f8165c32-01fe-11e8-918b-e4c157199c03.png)

**Comment by mortenwh** [comment]
Comments regarding the topography domain:

        In [4]: topo = Nansat('/mnt/10.11.12.231/sat_auxdata/dem/gmted30/gmted2010_30.vrt') 
        In [5]: tlon,tlat=topo.get_border()
        In [7]: print tlon.min(), tlon.max()
        -180.000138889 143.999861111
        In [8]: print tlat.min(), tlat.max()
        -90.0001388889 89.9998611111

This is the clue - the rounding errors cause the problems. In the above plot, the topography border isn't shown at all (given that the maximum longitude is 144 degrees [also too low..]), there should be a line south-north crossing eastern Australia. If we create a new domain based on the topography borders;

        topo_dom = Domain(NSR(3857),'-lle %f %f %f %f -tr 1000 1000' % (tlon.min(), tlat.min(), tlon.max(), tlat.max()))

we get the following:

![screen shot 2018-01-26 at 10 52 59](https://user-images.githubusercontent.com/109061/35434345-1c97eb56-0287-11e8-8a17-03c3c574fb4a.png)

Clearly no overlap/intersection...  Modifying slightly:

        topo_dom = Domain(NSR(3857),'-lle %f %f %f %f -tr 1000 1000' % (tlon.min()+.1, tlat.min()+.1, tlon.max(), tlat.max()))

![screen shot 2018-01-26 at 10 55 49](https://user-images.githubusercontent.com/109061/35434457-7f96d1ea-0287-11e8-9241-c05fbd573932.png)

Note the line crossing Australia - so this is as expected. Then, check intersection and overlap;

        geom_topo = topo_dom.get_border_geometry()
        ngeom=n.get_border_geometry()

        In [31]: geom_topo.Overlaps(ngeom)
        Out[31]: False
        In [32]: geom_topo.Intersects(ngeom)
        Out[32]: True

So, everything should be ok, except two things:

1. To be consistent, the function ```Domain.overlaps``` should use ```osgeo.ogr.Geometry.Overlaps``` and we should have a new function ```Domain.intersects``` which uses ```osgeo.ogr.Geometry.Intersects``` - or are these domain functions obsolete? What do you think?
2. The rounding errors in the gmted2010 topography data needs to be resolved in some way....
