### ISSUE TITLE
Installation problem about os.environ['LIB']

### ISSUE THREAD

**Issue by gwangxiangyi** [nansencenter/nansat#197]
My computer system is windows7 64 bit. I have installed the external packages before installing Nansat following the instructions on this website, https://github.com/nansencenter/nansat/wiki/Required-libs. When I installed Nansat using python, I get this error message:

Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
================ RESTART: F:\installer\python2.7\Lib\setup.py ================

Traceback (most recent call last):
  File "F:\installer\python2.7\Lib\setup.py", line 83, in <module>
    path = os.environ['LIB'].split(';')
  File "F:\installer\python2.7\lib\os.py", line 425, in __getitem__
    return self.data[key.upper()]
KeyError: 'LIB'

I don't know the meaning of the error, and how to deal with it?
THANKS!

**Comment by akorosov** [comment]
Hi @gwangxiangyi !
currently Nansat works on linux and mac environments. On windows it requires visual c compiler to be installed.
The error you show is related to Python installation on Windows and I don't know the reason for it.

I can recommend to install a virtual machine with Linux and then follow a recipe given in the README.txt
Good luck!

**Comment by gwangxiangyi** [comment]
Thank you for your advice!
I would like to know if Nansat can be used on windows successfully, and is it easy to install on windows by visual c compiler? Can you tell me a detail installation method.
Best regards,
Wang Xiangyi

在2017-09-13 15:58:38，王相宜2016206440007@whu.edu.cn写道：

Hi @gwangxiangyi !
currently Nansat works on linux and mac environments. On windows it requires visual c compiler to be installed.
The error you show is related to Python installation on Windows and I don't know the reason for it.

I can recommend to install a virtual machine with Linux and then follow a recipe given in the README.txt
Good luck!
