### ISSUE TITLE
Problem in installing nansat 

### ISSUE THREAD

**Issue by Ghazal87** [nansencenter/nansat#198]
I tried to install nansat with the following commands. every thing was fine accept the last command fail and get problem as the following  

# download the latest version of miniconda
wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh 

# make it executable
chmod +x miniconda.sh

# install miniconda virtual environment
./miniconda.sh -b -f -p $HOME/miniconda

# activate the miniconda environment
export PATH=$HOME/miniconda/bin/:$PATH

# update miniconda packages and metadata
conda update -q --yes conda

# install all requirements from conda-forge channel
conda install -q --yes -c conda-forge qt numpy scipy matplotlib nose pillow basemap netcdf4 gdal

# configure environment
export GDAL_DATA=$HOME/miniconda/share/gdal/
export GEOS_DIR=$HOME/miniconda/

pip install https://github.com/nansencenter/nansat/archive/master.tar.gz**
Collecting https://github.com/nansencenter/nansat/archive/master.tar.gz
  Downloading https://github.com/nansencenter/nansat/archive/master.tar.gz (1.1MB)
    100% |████████████████████████████████| 1.1MB 359kB/s 
Requirement already satisfied: Pillow in ./miniconda/lib/python2.7/site-packages (from nansat==0.6.15)
Requirement already satisfied: pythesint in ./miniconda/lib/python2.7/site-packages (from nansat==0.6.15)
Requirement already satisfied: cfunits in ./miniconda/lib/python2.7/site-packages (from nansat==0.6.15)
Requirement already satisfied: olefile in ./miniconda/lib/python2.7/site-packages (from Pillow->nansat==0.6.15)
Requirement already satisfied: PyYAML in ./miniconda/lib/python2.7/site-packages (from pythesint->nansat==0.6.15)
Requirement already satisfied: requests in ./miniconda/lib/python2.7/site-packages (from pythesint->nansat==0.6.15)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./miniconda/lib/python2.7/site-packages (from requests->pythesint->nansat==0.6.15)
Requirement already satisfied: idna<2.7,>=2.5 in ./miniconda/lib/python2.7/site-packages (from requests->pythesint->nansat==0.6.15)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in ./miniconda/lib/python2.7/site-packages (from requests->pythesint->nansat==0.6.15)
Requirement already satisfied: certifi>=2017.4.17 in ./miniconda/lib/python2.7/site-packages (from requests->pythesint->nansat==0.6.15)
Installing collected packages: nansat
  Running setup.py install for nansat ... error
    Complete output from command /home/ghazal/miniconda/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-LQBkWd-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-tydUo6-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/nansat_integration_tests
    copying nansat_integration_tests/test_mappers.py -> build/lib.linux-x86_64-2.7/nansat_integration_tests
    copying nansat_integration_tests/test_netcdf_cf_mappers.py -> build/lib.linux-x86_64-2.7/nansat_integration_tests
    copying nansat_integration_tests/__init__.py -> build/lib.linux-x86_64-2.7/nansat_integration_tests
    copying nansat_integration_tests/mapper_test_archive.py -> build/lib.linux-x86_64-2.7/nansat_integration_tests
    copying nansat_integration_tests/test_radarsat2.py -> build/lib.linux-x86_64-2.7/nansat_integration_tests
    creating build/lib.linux-x86_64-2.7/nansat
    copying nansat/node.py -> build/lib.linux-x86_64-2.7/nansat
    copying nansat/pointbrowser.py -> build/lib.linux-x86_64-2.7/nansat
    copying nansat/domain.py -> build/lib.linux-x86_64-2.7/nansat
    copying nansat/nansatmap.py -> build/lib.linux-x86_64-2.7/nansat
    copying nansat/vrt.py -> build/lib.linux-x86_64-2.7/nansat
    copying nansat/nsr.py -> build/lib.linux-x86_64-2.7/nansat
    copying nansat/figure.py -> build/lib.linux-x86_64-2.7/nansat
    copying nansat/nansat.py -> build/lib.linux-x86_64-2.7/nansat
    copying nansat/mosaic.py -> build/lib.linux-x86_64-2.7/nansat
    copying nansat/__init__.py -> build/lib.linux-x86_64-2.7/nansat
    copying nansat/tools.py -> build/lib.linux-x86_64-2.7/nansat
    creating build/lib.linux-x86_64-2.7/nansat/tests
    copying nansat/tests/test_pixelfunctions.py -> build/lib.linux-x86_64-2.7/nansat/tests
    copying nansat/tests/test_mosaic.py -> build/lib.linux-x86_64-2.7/nansat/tests
    copying nansat/tests/test_domain.py -> build/lib.linux-x86_64-2.7/nansat/tests
    copying nansat/tests/test_nansat.py -> build/lib.linux-x86_64-2.7/nansat/tests
    copying nansat/tests/test_figure.py -> build/lib.linux-x86_64-2.7/nansat/tests
    copying nansat/tests/test_nansatmap.py -> build/lib.linux-x86_64-2.7/nansat/tests
    copying nansat/tests/test_node.py -> build/lib.linux-x86_64-2.7/nansat/tests
    copying nansat/tests/test_tools.py -> build/lib.linux-x86_64-2.7/nansat/tests
    copying nansat/tests/test_nsr.py -> build/lib.linux-x86_64-2.7/nansat/tests
    copying nansat/tests/__init__.py -> build/lib.linux-x86_64-2.7/nansat/tests
    copying nansat/tests/nansat_test_data.py -> build/lib.linux-x86_64-2.7/nansat/tests
    copying nansat/tests/test_pointbrowser.py -> build/lib.linux-x86_64-2.7/nansat/tests
    creating build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_generic.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_geostationary.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_obpg_l2.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_globcolour_l3b.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_gtopo30.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_asar.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_opendap_sstcci.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_metno_hires_seaice.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_opendap_globcurrent.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_aapp_l1b.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_obpg_l3.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_hirlam_wind_netcdf.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_pathfinder52.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_hirlam.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_smos_mat.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_ncep.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_amsr2_l1r.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_nora10_local_vpv.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_kmss.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_opendap_globcurrent_thredds.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/envisat.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_amsr2_l3.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_ascat_nasa.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_ecmwf_metno.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_mod44w.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_opendap_arome.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_arome.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_opendap_osisaf.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_opendap.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_opendap_occci.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/hdf4_mapper.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_ncep_wind.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/__init__.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_amsre_uham_leadfraction.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/globcolour.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_modis_l1.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_ocean_productivity.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_sentinel1_l1.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_netcdf_cf.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_globcolour_l3m.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_radarsat2.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_opendap_siwtacsst.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_landsat.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_viirs_l1.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_aapp_l1c.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_meris_l1.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_emodnet.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_goci_l1.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_ncep_wind_online.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_meris_l2.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_aster_l1b.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_case2reg.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_csks.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/obpg.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_aster_l1a.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_metno_local_hires_seaice.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_sentinel1a_l2.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/opendap.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/mapper_obpg_l2_nc.py -> build/lib.linux-x86_64-2.7/nansat/mappers
    creating build/lib.linux-x86_64-2.7/nansat/fonts
    copying nansat/fonts/DejaVuSans.ttf -> build/lib.linux-x86_64-2.7/nansat/fonts
    copying nansat/mappers/get_inv.pl -> build/lib.linux-x86_64-2.7/nansat/mappers
    copying nansat/mappers/get_grib.pl -> build/lib.linux-x86_64-2.7/nansat/mappers
    creating build/lib.linux-x86_64-2.7/nansat/tests/data
    copying nansat/tests/data/some_xml_file.xml -> build/lib.linux-x86_64-2.7/nansat/tests/data
    copying nansat/tests/data/arctic.nc -> build/lib.linux-x86_64-2.7/nansat/tests/data
    copying nansat/tests/data/nansat_logo_s.png -> build/lib.linux-x86_64-2.7/nansat/tests/data
    copying nansat/tests/data/stere.tif -> build/lib.linux-x86_64-2.7/nansat/tests/data
    copying nansat/tests/data/points.shp -> build/lib.linux-x86_64-2.7/nansat/tests/data
    copying nansat/tests/data/map.tif -> build/lib.linux-x86_64-2.7/nansat/tests/data
    copying nansat/tests/data/points.shx -> build/lib.linux-x86_64-2.7/nansat/tests/data
    copying nansat/tests/data/points.dbf -> build/lib.linux-x86_64-2.7/nansat/tests/data
    copying nansat/tests/data/complex.nc -> build/lib.linux-x86_64-2.7/nansat/tests/data
    copying nansat/tests/data/gcps.tif -> build/lib.linux-x86_64-2.7/nansat/tests/data
    running build_ext
    building 'nansat._pixfun' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/nansat
    creating build/temp.linux-x86_64-2.7/nansat/pixelfunctions
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ghazal/miniconda/include -I/home/ghazal/miniconda/include/python2.7 -c nansat/pixelfunctions/pixelfunctions.c -o build/temp.linux-x86_64-2.7/nansat/pixelfunctions/pixelfunctions.o -fPIC -Wall -Wno-long-long -pedantic -O3
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/ghazal/miniconda/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-LQBkWd-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-tydUo6-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-LQBkWd-build/

**Comment by akorosov** [comment]
you need to install gcc
sudo apt-get install build-essential
