### ISSUE TITLE
download sentinel 1 image for sea ice drift 

### ISSUE THREAD

**Issue by Ghazal87** [nansencenter/nansat#199]
**I tried to download the first image from sentinel 1 that was used to obtain sea ice drift through the following command in linux** 

wget ftp://ftp.nersc.no/pub/nansat/test_data/generic/S1A_EW_GRDM_1SDH_20161005T142446_20161005T142546_013356_0154D8_C3EC.SAFE.tif

## and I get the following response:

--2017-11-06 22:03:18--  ftp://ftp.nersc.no/pub/nansat/test_data/generic/S1A_EW_GRDM_1SDH_20161005T142446_20161005T142546_013356_0154D8_C3EC.SAFE.tif
           => ‘S1A_EW_GRDM_1SDH_20161005T142446_20161005T142546_013356_0154D8_C3EC.SAFE.tif’
Resolving ftp.nersc.no (ftp.nersc.no)... 158.37.60.245
Connecting to ftp.nersc.no (ftp.nersc.no)|158.37.60.245|:21... connected.
Logging in as anonymous ... 
Error in server response, closing control connection.
Retrying.

**it seems that I could not get access to the server  in order to download the image

Could anyone help me to dwonload this image and the next one and thanks in advance**

**Comment by aleksandervines** [comment]
Hi,

I tested just now, and everything seems to be fine with the server and the specific image you requested.

Could you please try again?

Cheers

**Comment by Ghazal87** [comment]
It did not work, I tried more than ten times and I still have the same response. Therefore, would you mind if it is possible to download them for me, the two SAR images of sentinel1?

Thanks in advance.

Ghazal

**Comment by akorosov** [comment]
Hi @Ghazal87 ,
if you enter ftp://ftp.nersc.no/pub/nansat/test_data/generic/ in your browser, can you see the directory content?

**Comment by Ghazal87** [comment]
I can not see the directory content? the browser is loading and no response.

**Comment by akorosov** [comment]
Ok, I've uploaded the files onto github. You can download the files here:

https://github.com/nansencenter/sea_ice_drift_test_files/raw/master/S1A_EW_GRDM_1SDH_20161005T142446_20161005T142546_013356_0154D8_C3EC.SAFE.tif
https://github.com/nansencenter/sea_ice_drift_test_files/raw/master/S1B_EW_GRDM_1SDH_20161005T101835_20161005T101935_002370_004016_FBF1.SAFE.tif

or clone the repo:
https://github.com/nansencenter/sea_ice_drift_test_files.git

**Comment by Ghazal87** [comment]
Thank you very much.
