### ISSUE TITLE
Can numpy check in setup.py be moved to requirements?

### ISSUE THREAD

**Issue by aleksandervines** [nansencenter/nansat#212]
I want to move this:
```
# Check if required packages are installed
try:
    import numpy
except ImportError:
    raise ImportError(import_error_msg % 'numpy')
```

Into here:

```
REQS                = [
                        "Pillow",
                        "pythesint",
                        "cfunits",
                        "numpy"
                    ]
```

Why?
Well, simplify things.

Why should it work?
If none of the other dependencies you have already installed is built on numpy (i.e. gdal is not built based on numpy, and scipy/matplotlib is not available) then whatever latest numpy version can be installed from pip.
If some of the already installed dependencies have numpy, this will not install it as it's already available.

**Comment by akorosov** [comment]
@aleksandervines , can you check the pull request please?
