### ISSUE TITLE
Incorrect conda parameter in instalation docs

### ISSUE THREAD

**Issue by korvinos** [nansencenter/nansat#219]
In part **Install dependencies from Anaconda** 

`conda install –yes -c conda-forge pythesint numpy scipy=0.18.1 matplotlib basemap netcdf4 gdal pillow urllib3`

**Has to be**

`conda install -–yes -c conda-forge pythesint numpy scipy=0.18.1 matplotlib basemap netcdf4 gdal pillow urllib3`

**Comment by aleksandervines** [comment]
Well spotted. I mixed -y and --yes

I think -y should be used though, to shorten it by 3 characters :)

**Comment by korvinos** [comment]
@akorosov The issue still there. Why did you close that?
