### ISSUE TITLE
Installation with pip fails because of old version in pip 

### ISSUE THREAD

**Issue by korvinos** [nansencenter/nansat#220]
I'm trying to install nansat with `pip install nansat` in the python 3.6 environment on VM (Dependencies has been installed with conda). 

As result, I get this message:

```
(phd-py36) vagrant@vagrant-ubuntu-trusty-64$ pip install --no-cache-dir nansat
Collecting nansat
  Downloading nansat-0.6.17.tar.gz (1.0MB)
    100% |████████████████████████████████| 1.1MB 6.0MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-c9zhgh3h/nansat/setup.py", line 146
        print 'WARNING: CONDA_PREFIX could not be found, ' +\
                                                         ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print 'WARNING: CONDA_PREFIX could not be found, ' +\)?
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-c9zhgh3h/nansat/

```

The message apparently shows that pip tries to install previous version of the package. @aleksandervines, Could you tell me please, what can I do with that?

**Comment by aleksandervines** [comment]
Wait until I've released 1.0.0. on pip, as I'm currently working on it. I've just been sidetracked by different things whole day.

**Comment by korvinos** [comment]
@aleksandervines thanks :)

**Comment by aleksandervines** [comment]
I created a sdits and uploaded, unfortunately it has issues on python2 ref. #224 but it seems to work on python3.

**Comment by korvinos** [comment]
@aleksandervines yeah, that works fine with python 3.6 now! :)

**Comment by aleksandervines** [comment]
This issue can be is closed then. Will fix the bug in the other issue.
