### ISSUE TITLE
Update docs/convention on how to work with hotfixes

### ISSUE THREAD

**Issue by aleksandervines** [nansencenter/nansat#222]
Is needed :)

**Comment by aleksandervines** [comment]
+9. HOTFIX workflow: branch from master into hotfixNNN_title (NNN = ticket number), update tests,
+   fix the bug, increment micro version, test, merge into master and into develop, delete branch.

Is the only change that should be in that branch. you have a lot more. Also, I thought we agreed on a different procedure: Merge into master, then merge master into develop.

However, there are some other suggestions that seems to be more popular:
https://gist.github.com/wildlyinaccurate/daec7910958330a64754

I like the "rebase workflow" described in there. Can we go for that? I like rebase!

**Comment by akorosov** [comment]
Yes, I'll rewrite 'merge from master into develop'

I'm one of the people that feel uncomfortable with rebase. I'm afraid to introduce yet another procedure (git command) to be used by the nansat developers.

**Comment by aleksandervines** [comment]
I think you should specify the procedure even more, so we always fast-forward when we actually do the pull into master/develop.

branch from master into hotfixNNN_title (NNN = ticket number), update tests,
fix the bug, increment micro version, test, **merge master into your branch (if there have been commits 
 in master since you branched), verify that Travis passes**, merge into master with `--ff-only`, **Possibly something like that here too, so we ensure that develop does not fail on the merge**,merge master into develop,
delete the hotfix branch.

It could be that using pull-requests will test the merge on Travis for us, and simplify things. Should look into that.

**Comment by akorosov** [comment]
@aleksandervines, OK now?

**Comment by mortenwh** [comment]
Is this added to the docs now?

**Comment by mortenwh** [comment]
There are a few things on the last points that should be changed. I'll propose an update...
