### ISSUE TITLE
automatically generated docs does not work 

### ISSUE THREAD

**Issue by aleksandervines** [nansencenter/nansat#231]
http://nansat.readthedocs.io/en/latest/source/nansat.html

**Comment by mortenwh** [comment]
This is now solved. Worked first time with 833c9ec - I had to reset the webhooks

**Comment by aleksandervines** [comment]
I don't see that it works..

**Comment by aleksandervines** [comment]
To clarify. When I go to http://nansat.readthedocs.io/en/latest/source/nansat.html#submodules I only see the headings for the different modules, not the actual documentation itself.

**Comment by aleksandervines** [comment]
I guess #236 covers this. But why generate a new issue when this already exists?

**Comment by mortenwh** [comment]
This and #236 are not the same issues - this issue was about the binding between readthedocs and github. #236 is about compliling the docstrings within the code...

**Comment by aleksandervines** [comment]
We can agree to disagree.
