### ISSUE TITLE
Duplicated code in nansat.__init__

### ISSUE THREAD

**Issue by aleksandervines** [nansencenter/nansat#246]
These two lines are exectued twice:

```
pixfun = importlib.import_module(pixfun_module_name)
pixfun.registerPixelFunctions()
```

I'm guessing this is because of an automated merge that was not thoroughly reviewed. Should be easy peasy to solve.

I'm guessing that we still "allow" nansat to be run without compiling pixel functions. If so, the ones inside the try-except should be kept.

**Comment by mortenwh** [comment]
this can be closed now, right?
