### ISSUE TITLE
NansatGDALError: Cannot read array from band None after get_super_vrt()

### ISSUE THREAD

**Issue by korvinos** [nansencenter/nansat#260]
During execution of my code (class inherit Nansat) a band is created and added to the Nansat object. Everething work fine before adding, I open a file and can read data. But after add_band, I get `NansatGDALError`: 
```

[before add band]
ipdb> self[1]
array([[16.619406, 16.685623, 16.75155 , ..., 26.19031 , 26.228886,
        26.26739 ],
       [16.619114, 16.685333, 16.751263, ..., 26.19013 , 26.228708,
        26.267212],
       [16.618822, 16.685045, 16.750973, ..., 26.189953, 26.228529,
        26.267033],
       ...,
       [16.11988 , 16.188236, 16.256271, ..., 25.88698 , 25.926062,
        25.965067],
       [16.119532, 16.187887, 16.255926, ..., 25.88677 , 25.925852,
        25.964857],
       [16.11918 , 16.18754 , 16.255579, ..., 25.88656 , 25.925642,
        25.964647]], dtype=float32)

[trying to add band to obj]
self.add_band(array=lf, parameters={'name': 'land_mask'})

[after add band]
ipdb> self[1]
NansatGDALError: Cannot read array from band None
```

I made some tests, and found that data is corrupted after:

`[Nansat, add_bands, line 357] self.vrt = self.vrt.get_super_vrt()`

Unfortunately, I could not trace the error after that because of the very complicated structure of the vrt.

**Comment by akorosov** [comment]
@korvinos , check with @jeong1park and close the issue.

**Comment by akorosov** [comment]
@korvinos , what is the status here?

**Comment by korvinos** [comment]
@akorosov the problem was in custom mapper, it worked
