### ISSUE TITLE
Failing test_open_gcps (nansat.tests.test_nansat.NansatTest)

### ISSUE THREAD

**Issue by mortenwh** [nansencenter/nansat#267]
test_open_gcps (in nansat.tests.test_nansat.NansatTest) fails on my local vm but seems to pass on Travis CI. Is this correct? Can anyone else check this on their local system as well?

**Comment by aleksandervines** [comment]
Are we talking about master?

**Comment by aleksandervines** [comment]
And what python version?

**Comment by aleksandervines** [comment]
Works for me on Windows 64bit without compiling pixel functions.

(nansat-test-environment) C:\Users\alevin\Documents\nansat>nosetests nansat.tests.test_nansat:NansatTest.test_open_gcps
C:\Users\alevin\Documents\nansat\nansat\__init__.py:35: UserWarning: Cannot register C pixel functions!
                     Either nansat was not installed using setup.py or
                     pixel functions were not compiled automatically.
                     For development, use "python setup.py build_ext --inplace"
                     to compile pixel functions manually into the source tree.

  ''')
.
----------------------------------------------------------------------
Ran 1 test in 0.112s

OK

**Comment by mortenwh** [comment]
I use the `metsarvind` vm (i.e., ubuntu) with python2.7 and the master branch.

**Comment by akorosov** [comment]
Cannot reproduce the issue
