### ISSUE TITLE
Int64 missed in numpy_to_gdal_types

### ISSUE THREAD

**Issue by korvinos** [nansencenter/nansat#282]
A key:value pair for Int64 is missed in `nansat.tools.numpy_to_gdal_type` dictionary. Is that because gdal somehow does not support `Int64` or just a bug?

**Comment by akorosov** [comment]
I'm not sure. @korvinos, Can you check with GDAL please? If it is supported by GDAL - just add to the dictionary.

**Comment by korvinos** [comment]
@akorosov Yes, no problem, I can do that

**Comment by akorosov** [comment]
Gdal doesnt have int64
