### ISSUE TITLE
Missing attributes when using the class methods in VRT to create objects

### ISSUE THREAD

**Issue by mortenwh** [nansencenter/nansat#289]
I'm trying to use the class methods to create vrt objects. To my understanding, both the following should work:

```
vrt = VRT.from_array(array)
```

and

```
super(Mapper, self).from_lonlat(longitude, latitude)
```

The first is done in a helper class (in `gsarVRTs.py`) and the second is done in the mapper. The resulting VRT object should then be "complete" but the `create_band` method fails with the following error message:

```
File "/home/vagrant/miniconda/lib/python2.7/site-packages/nansat/vrt.py", line 1061, in create_band
    self.logger.debug('INPUTS: %s, %s " ' % (str(src), str(dst)))
AttributeError: 'NoneType' object has no attribute 'debug'
```

This seems like a bug... Is it a bug?

**Comment by akorosov** [comment]
VRT.from_lonlat() returns a VRT object. You cannot use first VRT.from_array() and then VRT.from_lonlat().

**Comment by mortenwh** [comment]
It should be possible when the source band is a vrt file, shouldn't it? E.g.:

```
look_u_VRT = VRT.from_array(look_direction_u)
look_v_VRT = VRT.from_array(look_direction_v)
lookVRT.create_band(
        [{
            'SourceFilename': look_u_VRT.filename,
            'SourceBand': 1
        },{
            'SourceFilename': look_v_VRT.filename,
            'SourceBand': 1
        }], {'PixelFunctionType': 'UVToDirectionTo'})
```

or

```
metaDict.append({
             'src': {
                 'SourceFilename': self.band_vrts['angle_of_incidence_VRT'].fileName,
                 'SourceBand': 1
             },
             'dst': {
                 'wkv': 'angle_of_incidence',
                 'name': 'incidence_angle'
            }
})
```

**Comment by mortenwh** [comment]
I have tested it a bit more now  - seems there is no bug. The usage `super(Mapper, self).from_lonlat(longitude, latitude)` is wrong. This will not modify the current object `self` but rather use the class method object `cls`. The correct initialisation would then be to use `self._init_from_lonlat(longitude, latitude)` or `super(Mapper, self)._init_from_lonlat(longitude, latitude)`. It seems we could benefit from using the latter method with super more consisently (see, e.g., https://rhettinger.wordpress.com/2011/05/26/super-considered-super/) although it is not necessary in this case...
