### ISSUE TITLE
Latest Sentinel-1 format breaks the mapper

### ISSUE THREAD

**Issue by Polarnix** [nansencenter/nansat#294]
Hi,

The latest version (IPF version 2.9) of the ESA Sentinel-1 L1 format breaks the mapper because the _noiseLut_ is now _noiseRangeLut_ and _noiseAzimuthLut_.  I created a quick workaround to fix this on Istjenesten's processing chain, and attach a couple of small patches (for mapper_sentinel1_l1.py and S1_EW_GRD_NoiseCorrection.py in the denoise-routine) that I'm using to keep things running using just the range denoise data until someone gets a chance to look into this further, and whether a IPF-version specific fix is necessary.

[mapper_sentinel1_l1_patch.txt](https://github.com/nansencenter/nansat/files/1807492/mapper_sentinel1_l1_patch.txt)
[S1_EW_GRD_NoiseCorrection_patch.txt](https://github.com/nansencenter/nansat/files/1807493/S1_EW_GRD_NoiseCorrection_patch.txt)

Cheers,

Nick

**Comment by akorosov** [comment]
Thank you, @Polarnix for the patches! The fix is coming soon to allow opening old and new files.

**Comment by mortenwh** [comment]
Thanks - this is now merged
