### ISSUE TITLE
Wrong filename in warnings.py

### ISSUE THREAD

**Issue by korvinos** [nansencenter/nansat#302]
Now: `# Name: exceptions.py`
Must be: `# Name: warnings.py`

**Comment by akorosov** [comment]
I would rather agree with Morten calling it 'exceptions.py', because all classes there inherit from Exception.
I suggest to close it as invalid.

**Comment by korvinos** [comment]
Well, then the file should be renamed to the exceptions.py

**Comment by mortenwh** [comment]
`warnings.py` contains warnings and inherits Warning, `exceptions.py` inherit from Exception. @korvinos is right...

**Comment by akorosov** [comment]
Now I see. It is the header that should be changed. Not the filename...
