### ISSUE TITLE
Vagrant configuration for Nansat

### ISSUE THREAD

**Issue by akorosov** [nansencenter/nansat#313]
Provide vagrant configuration for running a VM with Nansat:

* Add `Vagrantfile` to the root
* Add `provisioning` directory and the following content:
  * `site.yml` - configuration of the Nansat virtual machine
  * `galaxy_requirements.yml` - list of galaxy roles for installing conda
  * `conda_env_requirements.yml` - list of conda packages
  * `roles/nansat/tasks/main.yml` - task for Nansat installation (compile + update bashrc)

**Comment by akorosov** [comment]
Also figure out how Vagrant configuration can be tested...

**Comment by mortenwh** [comment]
It seems Vagrant doesn't install anything, not even conda. I can't run the tests after merging master into develop, following the changes in #375. I don't have time to handle installation issues now, but are we going to use vagrant still? If not, the vagrant config files should be removed. 

What about docker? Does it work for nansat now?

**Comment by akorosov** [comment]
Yes Docker works. Vagrant also works.
