### ISSUE TITLE
VRT._from_lonlat is called without kwargs

### ISSUE THREAD

**Issue by akorosov** [nansencenter/nansat#319]
#### Problem
`VRT._from_lonlat` is called without `**kwargs`. THat prevents specifying how many GCPs we want to generate from lon/lat arrays.

#### Solution
1. Add `**kwargs` to `vrt._init_from_lonlat(lon, lat)` in `VRT.from_lonlat()`
1. Add tests which modify number of GCPs
1. Add more options to `_init_from_lonlat`, e.g. `geolocation=True` for adding geolocation

**Comment by korvinos** [comment]
fixed in #339
