### ISSUE TITLE
Allow importing of nansat_mappers from several different projects

### ISSUE THREAD

**Issue by korvinos** [nansencenter/nansat#344]
Standart mechanism of importing custom mappers in Nansat is used a standard, predefined, name (nansat_mappers) to import all additional mappers before reading a file. Unfortunately, the more packages are based on Nansat, the more different mappers are requested. 

### Issue

It is not possible to import two directories with the same name from two different packages (see `openwind/nansat_mappers` and `sar-doppler/nansat_mappers`). Hence, a better way to import external nansat mappers should be found.

### Solution

Use `nansat_mappers` like a base name and allow adding suffixes (for instance, `nansat_mappers_openwind`). Therefore import all packages starts from `nansat_mappers*`.

**Comment by akorosov** [comment]
Actually the namespace package (nansat_mappers) can be located in several directories: https://www.python.org/dev/peps/pep-0420/
Don't forget to put
```
from pkgutil import extend_path
__path__ = extend_path(__path__, __name__)
```
into 
`nansat_mappers/__init__.py`

**Comment by mortenwh** [comment]
You can also make a folder nansat_mappers in your site_packages and then
link from that folder to each required mapper.

Den man. 16. jul. 2018, 10:09 skrev Anton Korosov <notifications@github.com
