### ISSUE TITLE
Conda installation fails on ubuntu 16.04

### ISSUE THREAD

**Issue by mortenwh** [nansencenter/nansat#360]
```
In [1]: import nansat
libncurses.so.6: cannot open shared object file: No such file or directory
...
ImportError: libncurses.so.6: cannot open shared object file: No such file or directory
In [2]: 
```
More or less followed instructions on readthedocs and installed nansat like this:

```
conda install -y -c conda-forge nansat
``` 

I'm running python 3.6 and conda 4.5.8

**Comment by jonbergh** [comment]
Using a Vagrant VM with **bento/ubuntu-16.04** with **conda-4.5.4**, and **python-3.6.5.final.0**, this works for me (though strange with different "latest" conda versions, why now 4.5.4?):

` conda create -n nansat -c conda-forge nansat`

**The hole procedure**

In Vagrant file (without provision!):
```
config.vm.box = "bento/ubuntu-16.04"
config.vm.box_url = "https://app.vagrantup.com/bento/boxes/ubuntu-16.04"
```

and from terminal
```
curl -O https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh
source ~/.bashrc
conda create -n nansat -c conda-forge nansat
source activate nansat
```

**Comment by akorosov** [comment]
We accidentally reproduced your error on johansen.
Installation gave this error when we installed it in the root environment. But when we installed into a virtual environment (`conda create -n py3nansat -c conda-froge nansat`) this error was gone.
there was a different error though, linked to conda-forge installation of nansat. I'm trying to find out...
