### ISSUE TITLE
nansat does not work with gdal 2.3.2

### ISSUE THREAD

**Issue by d-murashkin** [nansencenter/nansat#396]
When I try to open a geotiff with nansat (nansat.Nansat) it gives multiple errors related to gdal (version 2.3.2).
One of the tests fails with:
```
======================================================================
FAIL: Should add band and swath mask and return 0 in areas out of swath
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/d.murashkin/conda/envs/nansat/lib/python3.6/site-packages/nansat/tests/test_nansat.py", line 407, in test_add_band_and_reproject
    self.assertTrue(b1[0, 0] == 0)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 250 tests in 12.012s

FAILED (failures=1)
```

With gdal=2.2.4 everything works great.

**Comment by akorosov** [comment]
Two bugs were identified:
1. the new version of GDAL correctly interprets projection defined with NSR('+proj=stere')
Previously it was incorrectly transforming the points coordinates
2. VRT.get_shifted_vrt should not be applied to data in projection other than 4326.

The bugs were fixed and corresponding tests added. Test run both on new and old GDAL.

**Comment by akorosov** [comment]
I fixed bug but the build fails for windows. And it is a problem with installation of GDAL. I suggest to drop building and testing of Nansat on windows. We anyway provide VM/container approach....
@mortenwh, do you agree?

**Comment by mortenwh** [comment]
I agree :)

Den tir. 5. feb. 2019, 17:15 skrev Anton Korosov <notifications@github.com:

**Comment by mortenwh** [comment]
Is this also connected to the failing tests in develop? E.g.:
```
======================================================================
FAIL: test_reproject_gcps (nansat.tests.test_vrt.VRTTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/nansencenter/nansat/nansat/tests/test_vrt.py", line 639, in test_reproject_gcps
    self.assertEqual(vrt1.dataset.GetGCPs()[0].GCPY, 2217341.7476875726)
AssertionError: 1108670.8738437863 != 2217341.7476875726
----------------------------------------------------------------------
```
