### ISSUE TITLE
GDAL 3 and PyPi

### ISSUE THREAD

**Issue by ninsbl** [nansencenter/nansat#435]
Hi,

Ubuntu ships GDAL 2.4.2, while PyPi is already on GDAL 3.0.1.
Since setup.py in nansat does not specify any version for GDAL it is currently not possible to do a simple:
`pip3 install nansat`
on Ubuntu 18.04. One has to download nansat (`pip3 download nansat`), specify the GDAL version in setup.py and then install via
```
cd nansat-1.2.2
pip3 install -e .
```

Not sure if this should be addressed on Nansat or GDAL side... GDAL guys say it is rather a user issue. See:
http://osgeo-org.1560.x6.nabble.com/gdal-dev-Packages-on-PyPi-vs-Ubuntu-Fedora-td5417739.html

Maybe something like this in setup.py:
```
import subprocess
gdalversion = None
try:
    gdalversion = subprocess.check_output(['gdal-config', '--version']).decode('utf8').strip('\n')
except:
    print('Warning: Could not identify GDAL version, using latest from PyPi!')
if not gdalversion:
    gdal = 'gdal'
else:
    gdal = 'gdal=={}'.format(gdalversion)
# (...)
REQS                = [
                        "Pillow",
                        "pythesint",
                        "urllib3",
                        "numpy",
                        gdal,
                        "python-dateutil",
                    ]
```
But maybe that messes too much with PyPi?

BTW: Is nansat ready for GDAL 3?

**Comment by akorosov** [comment]
Thank you @ninsbl for your comment!
Nansat is not gdal3 ready. There are some backward incompatibilities in ogr thtat we did not fix yet. Besides there are problems to install and use gdal 3 with conda. The recommended way is to install the requirements with conda first:
```
conda create -y -n py3nansat gdal=2.4.2 numpy pillow netcdf4 scipy
conda activate py3nansat
pip install nansat
```
We actually need to update the README to reflect that gdal must be pinned.
 - [ ] update READE with gdal=2.4.2
