### ISSUE TITLE
Use nansat_base for testing and developing Nansat

### ISSUE THREAD

**Issue by aperrin66** [nansencenter/nansat#444]
Right now, the [nansat](https://github.com/nansencenter/nansat/blob/master/docker/Dockerfile_nansat) image is used for [testing in Travis CI](https://github.com/nansencenter/nansat/blob/master/.travis.yml#L11).
This could lead to unexpected behavior, since in this case **Nansat** is installed both as a package and as source code in `/src`.
A simple solution to avoid that would be to use the **nansat_base** image to run the tests in Travis CI.

Development on the source code of **Nansat** should also be conducted using the [nansat_base](https://github.com/nansencenter/nansat/blob/master/docker/Dockerfile_base) image, to avoid the same potential problems.

**Comment by akorosov** [comment]
Fixed in #448
