### ISSUE TITLE
Fix coveralls report

### ISSUE THREAD

**Issue by aperrin66** [nansencenter/nansat#446]
No data has been pushed to coveralls since [october 2019](https://coveralls.io/repos/50061/builds).
There are several problems which come from the fact that `coverage` is run inside the **nansat** container, and `coveralls` outside:
- the path in which these commands are run is not the same since the build directory is mounted to `/src`
- depending on the travis CI configuration and the docker image, `coverage` and `coveralls` might not use the same version of Python

The simplest way to fix this would be to run `coveralls` inside the container.
Several environment variables must be made available to the container for this to work:
- COVERALLS_REPO_TOKEN (must be set as a Travis CI repository variable or an encrypted value in the `.travis.yml` file)
- TRAVIS=true
- TRAVIS_JOB_ID
- TRAVIS_BRANCH
- TRAVIS_BRANCH
- TRAVIS_PULL_REQUEST

**Comment by akorosov** [comment]
Fixed in #448
