### ISSUE TITLE
Automate docker images building

### ISSUE THREAD

**Issue by aperrin66** [nansencenter/nansat#450]
We can make Travis CI build the docker images automatically:
- [x] Merge the two Dockerfiles into one, with multi-staging to be able to build `nansat_base` separately
- [x] Find a way to access `MOD44W.tgz` from Travis CI
- [x] Implement this workflow:
    - pull images
    - build images
    - run tests (directly on the installed package: `coverage run /opt/conda/bin/nosetests nansat.tests`)
    - push images if the tests where successful and if the build was triggered by a tag

**Comment by akorosov** [comment]
Good job!!!
