### ISSUE TITLE
proj_create fails when generating a domain

### ISSUE THREAD

**Issue by korvinos** [nansencenter/nansat#453]
Run inside the dev docker container based on akorosov/nansat. The code does not fail (i can create a Nansat obj based on it for example).

```
In [8]: from nansat import Domain, Nansat                                                                            

In [9]: d = Domain(4326, '-lle -180 -90 180 90 -tr 0.1 0.1')                                                         
pj_obj_create: Open of /opt/conda/share/proj failed

In [14]: d                                                                                                           
Out[14]: proj_create: Open of /opt/conda/share/proj failed

Domain:[3600 x 1800]
----------------------------------------
Projection(dataset):
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563]],
    PRIMEM["Greenwich",0],
    UNIT["degree",0.0174532925199433]]
----------------------------------------
Corners (lon, lat):
         (-180.00,  90.00)  (180.00,  90.00)
         (-180.00, -90.00)  (180.00, -90.00)
```

**Comment by aperrin66** [comment]
The conda base environment needs to be activated by running `source /opt/conda/bin/activate`.
The same error appears in Travis CI logs <https://travis-ci.org/nansencenter/nansat/builds/634748460>, we will need to get to the bottom of this.

**Comment by aperrin66** [comment]
Activating the conda environment before running the tests works: <https://travis-ci.org/aperrin66/nansat/builds/637491257>
However, it will be necessary to find a better solution: having to activate the environment each time you run the container is really inconvenient.

Some solutions would be:
- setting an entrypoint as suggested [here](https://pythonspeed.com/articles/activate-conda-dockerfile/)
- not using conda in the Dockerfile

**Comment by aperrin66** [comment]
@akorosov this might interest you
