### ISSUE TITLE
AttributeError: module 'yaml' has no attribute 'FullLoader'

### ISSUE THREAD

**Issue by jaimebayes** [nansencenter/nansat#457]
Hi, 

When I try to install nansat, it generates this error:
`pip install git+https://github.com/nansencenter/nansat.git`
ERROR: Failed building wheel for pythesint.

So, I try to install first pythesint, and it works well:
`pip install pythesint`
Requirement already satisfied: pythesint in /usr/local/lib/python3.6/dist-packages (1.4.7)

but when I import it:, generates this error:
`import pythesint`
AttributeError: module 'yaml' has no attribute 'FullLoader'

I am using google colab.
Any advice?

Thanks in advance, JL

**Comment by akorosov** [comment]
https://stackoverflow.com/questions/55551191/module-yaml-has-no-attribute-fullloader

пт, 24 янв. 2020 г. в 15:32, JBayes <notifications@github.com>:
