### ISSUE TITLE
mapper for high resolution band of Landsat8

### ISSUE THREAD

**Issue by asumak** [nansencenter/nansat#50]
Landsat8 includes different resolution bands. (band 1-7,9: 30-meters, band 8: 15-meters).
Currently the size of the 8th band is reduced to 50%.
If option is given, return band with full resolution of 8th band.

**Comment by asumak** [comment]
solved in 42b4b0a.
Remove 'mapper_ landsat_highresolution' and add 'resolution' option to 'mapper_landsat'.
If resolution = 'high', only high resolution data is returned.

**Comment by akorosov** [comment]
Closed in d43139c5dba1cb0938747c0bfbde28b68016e3a0
