### ISSUE TITLE
About pip install nansat

### ISSUE THREAD

**Issue by zdy1139** [nansencenter/nansat#511]
When I follow the instructions to install nansat, I met the problem. I use Anaconda to install. I just cannot 'pip install nansat'. 
![image](https://user-images.githubusercontent.com/55383671/144988555-239ab33e-c152-4426-bfe9-e39157a7eef0.png).
My python version is 3.8.0. How can I install nansat successfully?

**Comment by aperrin66** [comment]
Hi, it looks like pip does not manage to connect to the PyPI repository.
This is not directly linked to nansat, and there are several possible reasons for the problem:

- Maybe PyPI was not available at the time you ran the command. If that was the case, you can just run the command again after checking that you can reach https://pypi.python.org/simple.
- If you are using pip behind a proxy, you might need to specify the `--proxy` option (use `pip --help` to get the proper format for this option)
- Maybe you are using an obsolete pip version, in which case you can try to update it.

These are just off the top of my head, if the problem persists I encourage you to Google the error message to see if someone else ran into it.
