### ISSUE TITLE
version=0.0.0dev in setup.py forces pip to install older version of nansat

### ISSUE THREAD

**Issue by akorosov** [nansencenter/nansat#518]
When installing nansat with pip `pip install nansat` it complains about version=0.0.0dev in the setup.py and installs an older version 1.4.5
I suggest to always manually update the correct version of nansat in setup.py
I'll update manually to 1.5.2 and propose a new release

**Comment by aperrin66** [comment]
This problem has been fixed in version 1.6.2 (see #545)
