### ISSUE TITLE
Nansat and Domain methods should return status

### ISSUE THREAD

**Issue by akorosov** [nansencenter/nansat#54]
### Problem:
Such Nansat methods as e.g. reproject(), crop(), resize() etc. do not return status. They may do the job or raise error or quit silently. Not letting the master application know if the action was performed properly.

### Solution
Let every method return either requested value (e.g. shape() or get_border()) or at least status. 0 is default status which report that everything is fine. 1,2,3 and other values are returned if this or that problem encountered and nothing happened. Error is raised in a really bad situation.

### Misc
Default values for status can be in the 'Nansat conventions' document.

**Comment by asumak** [comment]
Fixed in a1554b4

**Comment by akorosov** [comment]
This is related to #146. But #146 is more general. Closing as wontifx
