### ISSUE TITLE
After installing the required dependency libraries, the following problems will occur when installing directly on Windows 10

### ISSUE THREAD

**Issue by LooperzZ** [nansencenter/nansat#543]
(nansat3.9) C:\Users\LooperzZ>pip install nansat
Collecting nansat
  Downloading nansat-1.6.1.tar.gz (1.1 MB)
     ---------------------------------------- 1.1/1.1 MB 12.9 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Discarding https://files.pythonhosted.org/packages/01/43/6835008c00f6f4115631945915a3268b0be9e2971efb1918e8bbdad48041/nansat-1.6.1.tar.gz (from https://pypi.org/simple/nansat/): Requested nansat from https://files.pythonhosted.org/packages/01/43/6835008c00f6f4115631945915a3268b0be9e2971efb1918e8bbdad48041/nansat-1.6.1.tar.gz has inconsistent version: expected '1.6.1', but metadata has '1.5.3'
  Using cached nansat-1.5.3.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\LooperzZ\AppData\Local\Temp\pip-install-5bqhlvq0\nansat_18e14e5247e74520b454ab088704d35e\setup.py", line 240, in <module>
          run_setup(skip_compile)
        File "C:\Users\LooperzZ\AppData\Local\Temp\pip-install-5bqhlvq0\nansat_18e14e5247e74520b454ab088704d35e\setup.py", line 201, in run_setup
          extra_link_args=extra_link_args)
      NameError: name 'extra_link_args' is not defined
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by aperrin66** [comment]
The package metadata problem has been fixed in version 1.6.2.
You can install it by running `pip install nansat==1.6.2`
