### ISSUE TITLE
nansat installation unexpected error

### ISSUE THREAD

**Issue by jwLuo6413** [nansencenter/nansat#550]
I follow the instructions following this link: https://github.com/nansencenter/nansat/blob/master/docs/source/installation.rst. After installing nansat and its optional packages, I try to use nansat read sentinel-1 zip file and Geotiff file. Both of them give me the same error like this: 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ljw/miniconda3/envs/py3nansat/lib/python3.7/site-packages/nansat/nansat.py", line 156, in __init__
    self.vrt = self._get_mapper(mapper, **kwargs)
  File "/home/ljw/miniconda3/envs/py3nansat/lib/python3.7/site-packages/nansat/nansat.py", line 1157, in _get_mapper
    tmp_vrt = nansatMappers[iMapper](self.filename, gdal_dataset, metadata, **kwargs)
  File "/home/ljw/miniconda3/envs/py3nansat/lib/python3.7/site-packages/nansat/mappers/mapper_sentinel1_l1.py", line 185, in __init__
    self.create_bands(metaDict)
  File "/home/ljw/miniconda3/envs/py3nansat/lib/python3.7/site-packages/nansat/vrt.py", line 926, in create_bands
    self.create_band(src, dst)
  File "/home/ljw/miniconda3/envs/py3nansat/lib/python3.7/site-packages/nansat/vrt.py", line 1007, in create_band
    dst['name'], wkv = self._create_band_name(dst)
  File "/home/ljw/miniconda3/envs/py3nansat/lib/python3.7/site-packages/nansat/vrt.py", line 706, in _create_band_name
    wkv_pti = pti.get_wkv_variable(str(wkv_dst))
  File "/home/ljw/miniconda3/envs/py3nansat/lib/python3.7/site-packages/pythesint/vocabulary.py", line 45, in find_keyword
    for d in self.get_list():
  File "/home/ljw/miniconda3/envs/py3nansat/lib/python3.7/site-packages/pythesint/json_vocabulary.py", line 22, in get_list
    result = json.load(opened_file)
  File "/home/ljw/miniconda3/envs/py3nansat/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/ljw/miniconda3/envs/py3nansat/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/ljw/miniconda3/envs/py3nansat/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ljw/miniconda3/envs/py3nansat/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I think maybe this relates with "pythesint", so I try to update local JSON vocabularies following this link: https://github.com/nansencenter/py-thesaurus-interface/tree/master. But when I try to run "import pythesint as pti; pti.update_cf_standard_name(version='20210119T185509')" or "import pythesint as pti; pti.update_cf_standard_name()", it gives me error like this:
Downloading and writing json file for cf_standard_name
/home/ljw/.local/share/pythesint/json
段错误

Can anyone give me some hints about this? How to fix it?

**Comment by aperrin66** [comment]
Hi @jwLuo6413, can you export your anaconda environment (see instructions [here](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#exporting-the-environment-yml-file)) and attach the `environment.yml` file in this conversation, so that I can try to reproduce that error?

**Comment by jwLuo6413** [comment]
@aperrin66 Thanks for your kindness :). Details about "environment.yml" shows below:
 
name: py3nansat
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - bzip2=1.0.8=hd590300_5
  - ca-certificates=2024.6.2=hbcca054_0
  - cairo=1.14.12=h80bd089_1005
  - cfitsio=3.470=hb60a0a2_2
  - cftime=1.6.2=py37hc105733_0
  - curl=7.68.0=hf8cf82a_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.6.2=h59595ed_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonttools=4.38.0=py37h540881e_0
  - freetype=2.12.1=h267a509_2
  - freexl=1.0.6=h166bdaf_1
  - gdal=2.4.2=py37h5f563d9_8
  - geos=3.7.2=he1b5a44_2
  - geotiff=1.5.1=hcd53e25_3
  - gettext=0.22.5=h59595ed_2
  - gettext-tools=0.22.5=h59595ed_2
  - giflib=5.1.7=h516909a_1
  - glib=2.56.2=had28632_1001
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - hdf4=4.2.15=h9772cbc_5
  - hdf5=1.10.4=nompi_h3c11f04_1106
  - icu=58.2=hf484d3e_1000
  - jpeg=9e=h0b41bf4_3
  - json-c=0.13.1=hbfbb72e_1002
  - kealib=1.4.10=h1978553_1003
  - kiwisolver=1.4.4=py37h7cecad7_0
  - krb5=1.16.4=h2fd8d38_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.40=hf3520f5_2
  - lerc=3.0=h9c3ff4c_0
  - libasprintf=0.22.5=h661eb56_2
  - libasprintf-devel=0.22.5=h661eb56_2
  - libblas=3.9.0=13_linux64_openblas
  - libboost-headers=1.85.0=ha770c72_1
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.9.0=13_linux64_openblas
  - libcurl=7.68.0=hda55be3_0
  - libdap4=3.20.4=hd3bb157_0
  - libdeflate=1.10=h7f98852_0
  - libedit=3.1.20191231=he28a2e2_2
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=13.2.0=h77fa898_7
  - libgdal=2.4.2=h182c168_8
  - libgettextpo=0.22.5=h59595ed_2
  - libgettextpo-devel=0.22.5=h59595ed_2
  - libgfortran-ng=7.5.0=h14aa051_20
  - libgfortran4=7.5.0=h14aa051_20
  - libgomp=13.2.0=h77fa898_7
  - libiconv=1.17=hd590300_2
  - libkml=1.3.0=h01aab08_1018
  - liblapack=3.9.0=13_linux64_openblas
  - libnetcdf=4.6.2=hbdf4f91_1001
  - libopenblas=0.3.18=hf726d26_0
  - libpng=1.6.43=h2797004_0
  - libpq=11.5=hd9ab2ff_2
  - libspatialite=4.3.0a=h57ae47a_1030
  - libsqlite=3.45.3=h2797004_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-ng=13.2.0=hc0a3c3a_7
  - libtiff=4.3.0=h0fcbabc_4
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.16=hd590300_0
  - libxml2=2.9.14=h74e7548_0
  - libzlib=1.2.13=h4ab18f5_6
  - matplotlib=3.5.3=py37h89c1867_2
  - matplotlib-base=3.5.3=py37hf395dca_2
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.5=h59595ed_0
  - netcdf4=1.5.1.2=py37had58050_0
  - numpy=1.21.6=py37h976b520_0
  - olefile=0.47=pyhd8ed1ab_0
  - openjpeg=2.3.1=hf7af979_3
  - openssl=1.1.1w=hd590300_0
  - packaging=23.2=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pillow=8.1.2=py37h4600e1f_0
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.34.0=h14c3975_1003
  - poppler=0.67.0=h2fc8fa2_1002
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=11.5=hc63931a_2
  - proj4=6.1.1=hc80f0dc_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pyqt=5.9.2=py37hcca6a23_4
  - python=3.7.8=h8bdb77d_2_cpython
  - python_abi=3.7=4_cp37m
  - qt=5.9.7=h5867ecd_1
  - readline=8.2=h8228510_1
  - scipy=1.5.3=py37h8911b10_0
  - setuptools=69.0.3=pyhd8ed1ab_0
  - sip=4.19.8=py37hf484d3e_1000
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.45.3=h2c6b66d_0
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.2=py37h540881e_0
  - typing-extensions=4.7.1=hd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - tzcode=2024a=h3f72095_0
  - unicodedata2=14.0.0=py37h540881e_1
  - uriparser=0.9.8=hac33072_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - xerces-c=3.2.2=hea5cb30_1003
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - basemap==1.4.1
      - basemap-data==1.3.2
      - certifi==2024.6.2
      - charset-normalizer==3.3.2
      - idna==3.7
      - nansat==1.6.2
      - pyproj==3.2.1
      - pyshp==2.3.1
      - pythesint==1.6.6
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.1
      - requests==2.31.0
      - urllib3==2.0.7
      - xdg==6.0.0
prefix: /home/ljw/miniconda3/envs/py3nansat

**Comment by aperrin66** [comment]
Your issue does look like you need to update the pythesint data. However, I am unable to reproduce the segmentation fault you get (if that is the error you get, I had to use google translate for this one).

Can you try to remove all pythesint data (in `~/.local/share/pythesint/` by default) and run the following after making sure your anaconda environment is activated?

`python -c 'import pythesint;pythesint.update_all_vocabularies()'`

**Comment by jwLuo6413** [comment]
@aperrin66 Thanks for your help and now I can use "Nansat" package normally. Actually, I still encounter another issue when I type 
"python -c 'import pythesint;pythesint.update_all_vocabularies()'" in the command line after activating 'py3nansat' environment. it shows below:

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /nansencenter/nersc-vocabularies/master/nansat_wkv.yml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9428fd3450>: Failed to establish a new connection: [Errno 111] Connection refused'))

It seems that this error associated with host 'raw.githubusercontent.com' connection, I solved this issue by searching its corresponding ipv4 address and added this address and host name in "hosts" file, which should be located in "C:\Windows\System32\drivers\etc\" directory in wIndows system.

Hope my problem-solving journey can benefit others who could come across the same issue like me in the future. Thanks again!
