### ISSUE TITLE
Longitude and latitude for ASAR should be calculated for each slice

### ISSUE THREAD

**Issue by mortenwh** [nansencenter/nansat#56]
At the moment (it looks like) we use first lines and the last last line for this. It is not exactly correct, and it shouldn't be too difficult to do it as per tile.

**Comment by asumak** [comment]
If lon/lat are nonlinear, how to interpolate with only the first and last lines for each slice? 
Is the function given anywhere? Kunt-Frode, do you know that?

**Comment by knutfrode** [comment]
I think this ticket must be outdated?
Present ASAR mapper contains lon/lat only as tie points, directly read from the raw file by GDAL.
https://github.com/nansencenter/nansat/blob/develop/nansat/mappers/mapper_asar.py

Incidence angle and SAR look direction, on the other hand, are stored in small arrays (same size as lon/lat GCP arrays), and are interpolated onto the full sized image by VRT.get_resized_vrt(). This I believe should be fine.

So if Morten agrees, I think this ticket can be closed.

**Comment by asumak** [comment]
Morten thinks present way is not adequately accurate.
I will ask him again.
