### ISSUE TITLE
Add RGB creation to Nansatmap

### ISSUE THREAD

**Issue by akorosov** [nansencenter/nansat#63]
pyplot.pcolormesh doesn't support RGB, only pseudocolor.
Add Nansatmap.imshow() which can be used to display RGB images.
Use extent parameter to define the scale of the image

**Comment by akorosov** [comment]
Instead of nmap.pcolormesh(array) a user should be able to call
nmap.imshow(rgb_image) to make a map with RGB raster data. rgb_image is 3D matrix with shape (width, height, 3) or (width, height, 4) for RGB or RGBA images.

**Comment by asumak** [comment]
Basemap.imshow() automatically set the extent.
Do we still need extent parameter or keep it as an optional argument?

**Comment by asumak** [comment]
solved (8a8dead)

**Comment by akorosov** [comment]
Close in f7d3a87ee202006c261a7659c1951526ad3705e3
