### ISSUE TITLE
Provide version for Python3

### ISSUE THREAD

**Issue by akorosov** [nansencenter/nansat#69]
### Problem Python 3 is becoming more and more used. All libraries that Nansat depend on have 2.X and 3.X versions. More people start to use Python and version 3 only. People will be studying Python 3 at the courses at NERSC. ### Solution We should provide Python 3 version of Nansat for each stable release. There is a tool 2to3 delivered with py3k which automatically translates the code. However, due to principal differences in the languages, these changes are not always optimal or may even not work at all. We should adapt the Nansat code and add new conventions which will make such translation painless (less painful, at least).

**Comment by neothemachine** [comment]
Just a tip, many projects (also myself) use the `six` library for that. Then you can have a single codebase with Python 2 and 3 support.

**Comment by asumak** [comment]
Thanks, Maik.
