### ISSUE TITLE
Reprojection to/from a domain with GCPs only works if GCPs are in lon-lat coordinate system

### ISSUE THREAD

**Issue by knutfrode** [nansencenter/nansat#73]
For images with GCPs (ASAR and Radarsat2) s.watermask() gives only zero values after reprojecting GCPs with

> > > s.reproject_GCPs(srs)

unless srs = '+proj=latlong' (i.e. as original GCP projection)

Does anyone have a clue why this happens?

**Comment by akorosov** [comment]
Fixed in 49f28997285c569bc93d857e7ca3b55d5b714d16
