### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by mortenwh** [nansencenter/nansat#91]
At the moment, the tutorial is also used for testing. This should be avoided, and the proper tests should be added to the `nansat.tests` package.

**Comment by aleksandervines** [comment]
Almost every commit seems to reduce the test coverage. That is not how it should work :)

https://coveralls.io/github/nansencenter/nansat?branch=develop

@mortenwh 
@akorosov

**Comment by akorosov** [comment]
Test coverage exceed 90%. Closing this generic issue. More tests to be added for new functions.
