### ISSUE TITLE
Make labels and gridlines at predefined positions in Figure

### ISSUE THREAD

**Issue by akorosov** [nansencenter/nansat#99]
Labels and gridlines are regular but uncontrolled in Figure.add_latlon_grids() and .add_latlon_labels()
Pass latTics and lonTics parameters to Figure.add_latlon_grids() and .add_latlon_labels()

**Comment by asumak** [comment]
solved in a37c8f6

**Comment by akorosov** [comment]
I have to create a NEW branch from DEVELOP and thus disregard all the commits here.
The new branch will be called:
**issue99-figure-gridlines**

**Comment by akorosov** [comment]
closed in bb9aa96
